[global]
dataFrameSerialization = "arrow"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
baseUrlPath = "file-import"
maxUploadSize = 50


[browser]
gatherUsageStats = false

[theme]
primaryColor="#6B73FF"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f7f8fa"
textColor="#202124"
font="sans serif"


[logger]
level = "info"


